# Generated by Django 6.0.6 on 2026-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_codigo', models.CharField(choices=[('1000', 'Inventario / Mercadería'), ('1001', 'Banco / Caja'), ('4000', 'Ventas'), ('2100', 'IVA Débito Fiscal'), ('2000', 'Proveedores (a pagar)'), ('1100', 'Clientes (a cobrar)')], max_length=10)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referencia_tipo', models.CharField(max_length=20)),
                ('referencia_id', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Libro Diario',
                'ordering': ['-fecha'],
            },
        ),
    ]
