# Generated by Django 6.0.6 on 2026-07-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('MT', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('LT', 'Litro'), ('BOL', 'Bolsa'), ('PAL', 'Pallet')], default='UN', max_length=3)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('pmp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuenta_stock', models.BooleanField(default=True, help_text='Si está activo, este producto descuenta stock automáticamente al confirmarse un pedido/factura. Desactivalo para productos por encargo, fletes, servicios o ítems que no se controlan en stock.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='stock.categoria')),
                ('proveedor_habitual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='stock.proveedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (compra / ajuste positivo)'), ('SALIDA', 'Salida (venta / ajuste negativo)'), ('AJUSTE', 'Ajuste manual de inventario')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stock_resultante', models.DecimalField(decimal_places=3, max_digits=14)),
                ('origen', models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('PEDIDO', 'Pedido / Venta mostrador'), ('AJUSTE_MANUAL', 'Ajuste manual')], max_length=20)),
                ('referencia_id', models.PositiveIntegerField(blank=True, help_text='ID de la Compra o el Pedido que originó este movimiento.', null=True)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stock.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
