# Generated by Django 6.0.7 on 2026-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_uso',
            field=models.TextField(blank=True, help_text='Ficha visible para todos los roles. Solo el Administrador puede editarla.', verbose_name='Descripción / uso'),
        ),
    ]
