# Generated by Django 6.0.7 on 2026-07-10 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='origen',
            field=models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('PEDIDO', 'Pedido / Venta mostrador'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('BOLETA', 'Boleta de stock'), ('AJUSTE_BOLETA', 'Corrección retroactiva de boleta'), ('IMPORTACION_EXCEL', 'Importación masiva desde Excel')], max_length=20),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (recepción de mercadería)'), ('SALIDA', 'Salida (retiro / consumo)')], max_length=10)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(blank=True, help_text='Quién recibió o despachó la mercadería (texto libre, ej. nombre del chofer o cliente).', max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto total del comprobante, si corresponde (respaldo cuando no hay adjunto).', max_digits=14)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='boletas/%Y/%m/')),
                ('ocr_texto', models.TextField(blank=True, help_text='Texto crudo detectado por OCR sobre el adjunto, guardado como respaldo.')),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletas_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Boletas',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='BoletaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('texto_original', models.CharField(blank=True, help_text='Línea de texto tal como la detectó el OCR, para poder auditar el match automático.', max_length=250)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, help_text='Score de confianza (0-100) del match automático por OCR, si esta línea vino de ahí.', max_digits=5, null=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.boleta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_boleta', to='stock.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('movimientos', models.ManyToManyField(blank=True, related_name='notas', to='stock.movimientostock')),
                ('productos', models.ManyToManyField(blank=True, related_name='notas', to='stock.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
