# Generated by Django 6.0.7 on 2026-07-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_movimientostock_origen_boleta_boletaitem_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='productos',
        ),
        migrations.CreateModel(
            name='NotaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_registrado', models.CharField(max_length=30)),
                ('nombre_registrado', models.CharField(max_length=200)),
                ('stock_registrado', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad_medida_registrada', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('MT', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('LT', 'Litro'), ('BOL', 'Bolsa'), ('PAL', 'Pallet')], max_length=3)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_snapshots', to='stock.nota')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.producto')),
            ],
            options={
                'verbose_name_plural': 'Snapshots de producto en notas',
            },
        ),
    ]
