# Generated by Django 6.0.7 on 2026-07-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_producto_descripcion_uso'),
        ('stock', '0003_remove_nota_productos_notaproducto'),
    ]

    operations = [
    ]
