# Generated by Django 6.0.6 on 2026-07-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartos_asignados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartos', to='repartos.vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RepartoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('direccion_entrega', models.CharField(blank=True, max_length=250)),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('NO_ENTREGADO', 'No entregado')], default='PENDIENTE', max_length=15)),
                ('observaciones_entrega', models.TextField(blank=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reparto_asignado', to='ventas.pedido')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='repartos.reparto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
