# Generated by Django 6.0.7 on 2026-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartopedido',
            name='estado_salida',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SALIO', 'Salió'), ('NO_SALIO', 'No salió')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='repartopedido',
            name='motivo_no_salida',
            field=models.TextField(blank=True),
        ),
    ]
