# Generated by Django 6.0.7 on 2026-07-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartos', '0002_repartopedido_estado_salida_and_more'),
        ('ventas', '0003_pedidolinea_cantidad_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartopedido',
            name='estado_salida',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Salida parcial'), ('SALIO', 'Salió completo'), ('NO_SALIO', 'No salió')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='repartopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartos_asignados', to='ventas.pedido'),
        ),
    ]
