# Generated by Django 6.0.7 on 2026-07-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_producto_descripcion_uso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('OFERTA', 'Oferta'), ('PRIORIDAD_VENTA', 'Prioridad de venta'), ('INFORMATIVO', 'Informativo')], default='INFORMATIVO', max_length=20)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Dejar en blanco si el aviso no vence automáticamente.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(blank=True, related_name='avisos', to='stock.producto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
