# Generated by Django 6.0.7 on 2026-07-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, help_text='Día estimado de entrega para las líneas que salen con reparto.', null=True),
        ),
        migrations.AddField(
            model_name='pedidolinea',
            name='sale_con_reparto',
            field=models.BooleanField(default=False, help_text='Si está activo, esta línea no se retira por mostrador: sale con el reparto y su stock se descuenta recién cuando el reparto marca su salida.'),
        ),
        migrations.AddField(
            model_name='pedidolinea',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Gestionado por el sistema: indica si esta línea ya impactó el stock (al confirmar el pedido, o al salir el reparto).'),
        ),
    ]
