# Generated by Django 6.0.7 on 2026-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_pedido_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidolinea',
            name='cantidad_salida',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Gestionado por el sistema: cuánto de esta línea ya salió del depósito con reparto (puede ser parcial; ver RepartoPedido.registrar_salida).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pedidolinea',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Gestionado por el sistema: indica si esta línea (retiro por mostrador) ya impactó el stock al confirmar el pedido.'),
        ),
    ]
